from __future__ import annotations

from BaseClasses import ItemClassification

# TODO find a way to refactor this such that I don't need separate lists for each location group/item group
# Probably involves splitting up LOCATION_NAME_TO_ID/ITEM_NAME_TO_ID and adding it back together

### LOCATION CONSTANTS ###

LOCATION_NAME_TO_ID = {
    # --- Technology Locations (IDs 1 - 92) ---
    "Archipelago The Wheel": 1,
    "Archipelago Agriculture": 2,
    "Archipelago Animal Husbandry": 3,
    "Archipelago Fishing": 4,
    "Archipelago Hunting": 5,
    "Archipelago Mysticism": 6,
    "Archipelago Archery": 7,
    "Archipelago Pottery": 8,
    "Archipelago Writing": 9,
    "Archipelago Sailing": 10,
    "Archipelago Masonry": 11,
    "Archipelago Mining": 12,
    "Archipelago Priesthood": 13,
    "Archipelago Bronze Working": 14,
    "Archipelago Polytheism": 15,
    "Archipelago Monotheism": 16,
    "Archipelago Meditation": 17,
    "Archipelago Monarchy": 18,
    "Archipelago Alphabet": 19,
    "Archipelago Mathematics": 20,
    "Archipelago Construction": 21,
    "Archipelago Code of Laws": 22,
    "Archipelago Metal Casting": 23,
    "Archipelago Compass": 24,
    "Archipelago Currency": 25,
    "Archipelago Horseback Riding": 26,
    "Archipelago Drama": 27,
    "Archipelago Calendar": 28,
    "Archipelago Iron Working": 29,
    "Archipelago Literature": 30,
    "Archipelago Aesthetics": 31,
    "Archipelago Banking": 32,
    "Archipelago Engineering": 33,
    "Archipelago Guilds": 34,
    "Archipelago Feudalism": 35,
    "Archipelago Machinery": 36,
    "Archipelago Civil Service": 37,
    "Archipelago Philosophy": 38,
    "Archipelago Optics": 39,
    "Archipelago Theology": 40,
    "Archipelago Paper": 41,
    "Archipelago Music": 42,
    "Archipelago Divine Right": 43,
    "Archipelago Economics": 44,
    "Archipelago Constitution": 45,
    "Archipelago Astronomy": 46,
    "Archipelago Democracy": 47,
    "Archipelago Education": 48,
    "Archipelago Chemistry": 49,
    "Archipelago Corporation": 50,
    "Archipelago Replaceable Parts": 51,
    "Archipelago Gunpowder": 52,
    "Archipelago Rifling": 53,
    "Archipelago Printing Press": 54,
    "Archipelago Nationalism": 55,
    "Archipelago Military Science": 56,
    "Archipelago Military Tradition": 57,
    "Archipelago Liberalism": 58,
    "Archipelago Railroad": 59,
    "Archipelago Electricity": 60,
    "Archipelago Assembly Line": 61,
    "Archipelago Steel": 62,
    "Archipelago Medicine": 63,
    "Archipelago Industrialism": 64,
    "Archipelago Communism": 65,
    "Archipelago Scientific Method": 66,
    "Archipelago Steam Power": 67,
    "Archipelago Fission": 68,
    "Archipelago Combustion": 69,
    "Archipelago Biology": 70,
    "Archipelago Physics": 71,
    "Archipelago Fascism": 72,
    "Archipelago Artillery": 73,
    "Archipelago Radio": 74,
    "Archipelago Flight": 75,
    "Archipelago Mass Media": 76,
    "Archipelago Plastics": 77,
    "Archipelago Computers": 78,
    "Archipelago Ecology": 79,
    "Archipelago Refrigeration": 80,
    "Archipelago Rocketry": 81,
    "Archipelago Robotics": 82,
    "Archipelago Satellites": 83,
    "Archipelago Laser": 84,
    "Archipelago Fiber Optics": 85,
    "Archipelago Advanced Flight": 86,
    "Archipelago Superconductors": 87,
    "Archipelago Composites": 88,
    "Archipelago Fusion": 89,
    "Archipelago Genetics": 90,
    "Archipelago Stealth": 91,
    "Archipelago Future Tech": 92,

    # --- Great Person Sanity Locations (IDs 101 - 170) ---
    "Great Scientist Check 1": 101,
    "Great Scientist Check 2": 102,
    "Great Scientist Check 3": 103,
    "Great Scientist Check 4": 104,
    "Great Scientist Check 5": 105,
    "Great Scientist Check 6": 106,
    "Great Scientist Check 7": 107,
    "Great Scientist Check 8": 108,
    "Great Scientist Check 9": 109,
    "Great Scientist Check 10": 110,

    "Great Engineer Check 1": 111,
    "Great Engineer Check 2": 112,
    "Great Engineer Check 3": 113,
    "Great Engineer Check 4": 114,
    "Great Engineer Check 5": 115,
    "Great Engineer Check 6": 116,
    "Great Engineer Check 7": 117,
    "Great Engineer Check 8": 118,
    "Great Engineer Check 9": 119,
    "Great Engineer Check 10": 120,

    "Great Prophet Check 1": 121,
    "Great Prophet Check 2": 122,
    "Great Prophet Check 3": 123,
    "Great Prophet Check 4": 124,
    "Great Prophet Check 5": 125,
    "Great Prophet Check 6": 126,
    "Great Prophet Check 7": 127,
    "Great Prophet Check 8": 128,
    "Great Prophet Check 9": 129,
    "Great Prophet Check 10": 130,

    "Great Artist Check 1": 131,
    "Great Artist Check 2": 132,
    "Great Artist Check 3": 133,
    "Great Artist Check 4": 134,
    "Great Artist Check 5": 135,
    "Great Artist Check 6": 136,
    "Great Artist Check 7": 137,
    "Great Artist Check 8": 138,
    "Great Artist Check 9": 139,
    "Great Artist Check 10": 140,

    "Great Merchant Check 1": 141,
    "Great Merchant Check 2": 142,
    "Great Merchant Check 3": 143,
    "Great Merchant Check 4": 144,
    "Great Merchant Check 5": 145,
    "Great Merchant Check 6": 146,
    "Great Merchant Check 7": 147,
    "Great Merchant Check 8": 148,
    "Great Merchant Check 9": 149,
    "Great Merchant Check 10": 150,

    "Great General Check 1": 151,
    "Great General Check 2": 152,
    "Great General Check 3": 153,
    "Great General Check 4": 154,
    "Great General Check 5": 155,
    "Great General Check 6": 156,
    "Great General Check 7": 157,
    "Great General Check 8": 158,
    "Great General Check 9": 159,
    "Great General Check 10": 160,

    "Great Spy Check 1": 161,
    "Great Spy Check 2": 162,
    "Great Spy Check 3": 163,
    "Great Spy Check 4": 164,
    "Great Spy Check 5": 165,
    "Great Spy Check 6": 166,
    "Great Spy Check 7": 167,
    "Great Spy Check 8": 168,
    "Great Spy Check 9": 169,
    "Great Spy Check 10": 170,

    # --- World Wonder Locations: (IDs 201 - 234) ---
    "The Pyramids": 201,
    "Stonehenge": 202,
    "The Oracle": 203,
    "The Parthenon": 204,
    "Chichen Itza": 205,
    "The Sistine Chapel": 206,
    "Notre Dame": 207,
    "The Taj Mahal": 208,
    "The Kremlin": 209,
    "The Eiffel Tower": 210,
    "The Statue of Liberty": 211,
    "The Pentagon": 212,
    "Hollywood": 213,
    "Rock 'n' Roll": 214,
    "Broadway": 215,
    "The Three Gorges Dam": 216,
    "The Space Elevator": 217,
    "The Hagia Sophia": 218,
    "The Great Lighthouse": 219,
    "The Colossus": 220,
    "The Hanging Gardens": 221,
    "The Great Library": 222,
    "Angkor Wat": 223,
    "The Spiral Minaret": 224,
    "The United Nations": 225,
    "The Great Wall": 226,
    "The Temple of Artemis": 227,
    "University of Sankore": 228,
    "Versailles": 229,
    "Mausoleum of Maussollos": 230,
    "The Statue of Zeus": 231,
    "Shwedagon Paya": 232,
    "The Apostolic Palace": 233,
    "Cristo Redentor": 234,

    # --- National Wonder Locations (IDs 241 - 253) ---
    "Heroic Epic": 241,
    "National Epic": 242,
    "Ironworks": 243,
    "Mt. Rushmore": 244,
    "Red Cross": 245,
    "Oxford University": 246,
    "Wall Street": 247,
    "Globe Theatre": 248,
    "Hermitage": 249,
    "Moai Statues": 250,
    "National Park": 251,
    "Forbidden Palace": 252,
    "West Point": 253,
}

### TECHSANITY LOCATION CONSTANTS ###
ARCHIPELAGO_ANCIENT_TECHS = [
    "Archipelago The Wheel",
    "Archipelago Agriculture",
    "Archipelago Animal Husbandry",
    "Archipelago Fishing",
    "Archipelago Hunting",
    "Archipelago Mysticism",
    "Archipelago Archery",
    "Archipelago Pottery",
    "Archipelago Writing",
    "Archipelago Sailing",
    "Archipelago Masonry",
    "Archipelago Mining",
    "Archipelago Priesthood",
    "Archipelago Bronze Working",
    "Archipelago Polytheism",
    "Archipelago Meditation",
    "Archipelago Monotheism",
]
ARCHIPELAGO_CLASSICAL_TECHS = [
    "Archipelago Calendar",
    "Archipelago Monarchy",
    "Archipelago Alphabet",
    "Archipelago Mathematics",
    "Archipelago Construction",
    "Archipelago Code of Laws",
    "Archipelago Metal Casting",
    "Archipelago Compass",
    "Archipelago Currency",
    "Archipelago Horseback Riding",
    "Archipelago Iron Working",
    "Archipelago Literature",
    "Archipelago Aesthetics",
    "Archipelago Drama",
]
ARCHIPELAGO_MEDIEVAL_TECHS = [
    "Archipelago Feudalism",
    "Archipelago Machinery",
    "Archipelago Civil Service",
    "Archipelago Guilds",
    "Archipelago Philosophy",
    "Archipelago Optics",
    "Archipelago Theology",
    "Archipelago Paper",
    "Archipelago Music",
    "Archipelago Divine Right",
    "Archipelago Banking",
    "Archipelago Engineering"
]
ARCHIPELAGO_RENAISSANCE_TECHS = [
    "Archipelago Economics",
    "Archipelago Constitution",
    "Archipelago Astronomy",
    "Archipelago Democracy",
    "Archipelago Education",
    "Archipelago Chemistry",
    "Archipelago Corporation",
    "Archipelago Replaceable Parts",
    "Archipelago Gunpowder",
    "Archipelago Rifling",
    "Archipelago Printing Press",
    "Archipelago Nationalism",
    "Archipelago Military Science",
    "Archipelago Military Tradition",
    "Archipelago Liberalism"
]
ARCHIPELAGO_INDUSTRIAL_TECHS = [
    "Archipelago Railroad",
    "Archipelago Electricity",
    "Archipelago Assembly Line",
    "Archipelago Steel",
    "Archipelago Medicine",
    "Archipelago Industrialism",
    "Archipelago Communism",
    "Archipelago Scientific Method",
    "Archipelago Steam Power",
    "Archipelago Fission",
    "Archipelago Combustion",
    "Archipelago Biology",
    "Archipelago Physics",
    "Archipelago Fascism",
    "Archipelago Artillery"
]
ARCHIPELAGO_MODERN_TECHS = [
    "Archipelago Radio",
    "Archipelago Flight",
    "Archipelago Mass Media",
    "Archipelago Plastics",
    "Archipelago Computers",
    "Archipelago Ecology",
    "Archipelago Refrigeration",
    "Archipelago Rocketry",
    "Archipelago Robotics",
    "Archipelago Satellites",
    "Archipelago Laser",
    "Archipelago Fiber Optics",
    "Archipelago Advanced Flight",
    "Archipelago Superconductors",
    "Archipelago Composites"
]
ARCHIPELAGO_FUTURE_TECHS = [
    "Archipelago Fusion",
    "Archipelago Genetics",
    "Archipelago Stealth",
    "Archipelago Future Tech"
]

### GPSANITY LOCATION CONSTANTS ###
GREAT_SCIENTIST_LOCATIONS = [
    "Great Scientist Check 1",
    "Great Scientist Check 2",
    "Great Scientist Check 3",
    "Great Scientist Check 4",
    "Great Scientist Check 5",
    "Great Scientist Check 6",
    "Great Scientist Check 7",
    "Great Scientist Check 8",
    "Great Scientist Check 9",
    "Great Scientist Check 10",
]
GREAT_ENGINEER_LOCATIONS = [
    "Great Engineer Check 1",
    "Great Engineer Check 2",
    "Great Engineer Check 3",
    "Great Engineer Check 4",
    "Great Engineer Check 5",
    "Great Engineer Check 6",
    "Great Engineer Check 7",
    "Great Engineer Check 8",
    "Great Engineer Check 9",
    "Great Engineer Check 10",
]
GREAT_PROPHET_LOCATIONS = [
    "Great Prophet Check 1",
    "Great Prophet Check 2",
    "Great Prophet Check 3",
    "Great Prophet Check 4",
    "Great Prophet Check 5",
    "Great Prophet Check 6",
    "Great Prophet Check 7",
    "Great Prophet Check 8",
    "Great Prophet Check 9",
    "Great Prophet Check 10",
]
GREAT_ARTIST_LOCATIONS = [
    "Great Artist Check 1",
    "Great Artist Check 2",
    "Great Artist Check 3",
    "Great Artist Check 4",
    "Great Artist Check 5",
    "Great Artist Check 6",
    "Great Artist Check 7",
    "Great Artist Check 8",
    "Great Artist Check 9",
    "Great Artist Check 10",
]
GREAT_MERCHANT_LOCATIONS = [
    "Great Merchant Check 1",
    "Great Merchant Check 2",
    "Great Merchant Check 3",
    "Great Merchant Check 4",
    "Great Merchant Check 5",
    "Great Merchant Check 6",
    "Great Merchant Check 7",
    "Great Merchant Check 8",
    "Great Merchant Check 9",
    "Great Merchant Check 10",
]
GREAT_GENERAL_LOCATIONS = [
    "Great General Check 1",
    "Great General Check 2",
    "Great General Check 3",
    "Great General Check 4",
    "Great General Check 5",
    "Great General Check 6",
    "Great General Check 7",
    "Great General Check 8",
    "Great General Check 9",
    "Great General Check 10",
]
GREAT_SPY_LOCATIONS = [
    "Great Spy Check 1",
    "Great Spy Check 2",
    "Great Spy Check 3",
    "Great Spy Check 4",
    "Great Spy Check 5",
    "Great Spy Check 6",
    "Great Spy Check 7",
    "Great Spy Check 8",
    "Great Spy Check 9",
    "Great Spy Check 10",
]

WORLD_WONDER_LOCATIONS = [
    "The Pyramids",
    "Stonehenge",
    "The Oracle",
    "The Parthenon",
    "Chichen Itza",
    "The Sistine Chapel",
    "Notre Dame",
    "The Taj Mahal",
    "The Kremlin",
    "The Eiffel Tower",
    "The Statue of Liberty",
    "The Pentagon",
    "Hollywood",
    "Rock 'n' Roll",
    "Broadway",
    "The Three Gorges Dam",
    "The Space Elevator",
    "The Hagia Sophia",
    "The Great Lighthouse",
    "The Colossus",
    "The Hanging Gardens",
    "The Great Library",
    "Angkor Wat",
    "The Spiral Minaret",
    "The United Nations",
    "The Great Wall",
    "The Temple of Artemis",
    "University of Sankore",
    "Versailles",
    "Mausoleum of Maussollos",
    "The Statue of Zeus",
    "Shwedagon Paya",
    "The Apostolic Palace",
    "Cristo Redentor",
]

NATIONAL_WONDER_LOCATIONS = [
    "Heroic Epic",
    "National Epic",
    "Ironworks",
    "Mt. Rushmore",
    "Red Cross",
    "Oxford University",
    "Wall Street",
    "Globe Theatre",
    "Hermitage",
    "Moai Statues",
    "National Park",
    "Forbidden Palace",
    "West Point",
]

### ITEM CONSTANTS ###

FULL_TECH_ARRAY = [
    "The Wheel",
    "Agriculture",
    "Animal Husbandry",
    "Fishing",
    "Hunting",
    "Mysticism",
    "Archery",
    "Pottery",
    "Writing",
    "Sailing",
    "Masonry",
    "Mining",
    "Priesthood",
    "Bronze Working",
    "Polytheism",
    "Monotheism",
    "Meditation",
    "Monarchy",
    "Alphabet",
    "Mathematics",
    "Construction",
    "Code of Laws",
    "Metal Casting",
    "Compass",
    "Currency",
    "Horseback Riding",
    "Drama",
    "Calendar",
    "Iron Working",
    "Literature",
    "Aesthetics",
    "Banking",
    "Engineering",
    "Guilds",
    "Feudalism",
    "Machinery",
    "Civil Service",
    "Philosophy",
    "Optics",
    "Theology",
    "Paper",
    "Music",
    "Divine Right",
    "Economics",
    "Constitution",
    "Astronomy",
    "Democracy",
    "Education",
    "Chemistry",
    "Corporation",
    "Replaceable Parts",
    "Gunpowder",
    "Rifling",
    "Printing Press",
    "Nationalism",
    "Military Science",
    "Military Tradition",
    "Liberalism",
    "Railroad",
    "Electricity",
    "Assembly Line",
    "Steel",
    "Medicine",
    "Industrialism",
    "Communism",
    "Scientific Method",
    "Steam Power",
    "Fission",
    "Combustion",
    "Biology",
    "Physics",
    "Fascism",
    "Artillery",
    "Radio",
    "Flight",
    "Mass Media",
    "Plastics",
    "Computers",
    "Ecology",
    "Refrigeration",
    "Rocketry",
    "Robotics",
    "Satellites",
    "Laser",
    "Fiber Optics",
    "Advanced Flight",
    "Superconductors",
    "Composites",
    "Fusion",
    "Genetics",
    "Stealth",
    "Future Tech",
]

# Every item must have a unique integer ID associated with it.
# We will have a lookup from item name to ID here that, in world.py, we will import and bind to the world class.
# Even if an item doesn't exist on specific options, it must be present in this lookup.
# All Techs should be 1 to 100, then other stuff above that
ITEM_NAME_TO_ID = {
    "The Wheel": 1,
    "Agriculture": 2,
    "Animal Husbandry": 3,
    "Fishing": 4,
    "Hunting": 5,
    "Mysticism": 6,
    "Archery": 7,
    "Pottery": 8,
    "Writing": 9,
    "Sailing": 10,
    "Masonry": 11,
    "Mining": 12,
    "Priesthood": 13,
    "Bronze Working": 14,
    "Polytheism": 15,
    "Monotheism": 16,
    "Meditation": 17,
    "Monarchy": 18,
    "Alphabet": 19,
    "Mathematics": 20,
    "Construction": 21,
    "Code of Laws": 22,
    "Metal Casting": 23,
    "Compass": 24,
    "Currency": 25,
    "Horseback Riding": 26,
    "Drama": 27,
    "Calendar": 28,
    "Iron Working": 29,
    "Literature": 30,
    "Aesthetics": 31,
    "Banking": 32,
    "Engineering": 33,
    "Guilds": 34,
    "Feudalism": 35,
    "Machinery": 36,
    "Civil Service": 37,
    "Philosophy": 38,
    "Optics": 39,
    "Theology": 40,
    "Paper": 41,
    "Music": 42,
    "Divine Right": 43,
    "Economics": 44,
    "Constitution": 45,
    "Astronomy": 46,
    "Democracy": 47,
    "Education": 48,
    "Chemistry": 49,
    "Corporation": 50,
    "Replaceable Parts": 51,
    "Gunpowder": 52,
    "Rifling": 53,
    "Printing Press": 54,
    "Nationalism": 55,
    "Military Science": 56,
    "Military Tradition": 57,
    "Liberalism": 58,
    "Railroad": 59,
    "Electricity": 60,
    "Assembly Line": 61,
    "Steel": 62,
    "Medicine": 63,
    "Industrialism": 64,
    "Communism": 65,
    "Scientific Method": 66,
    "Steam Power": 67,
    "Fission": 68,
    "Combustion": 69,
    "Biology": 70,
    "Physics": 71,
    "Fascism": 72,
    "Artillery": 73,
    "Radio": 74,
    "Flight": 75,
    "Mass Media": 76,
    "Plastics": 77,
    "Computers": 78,
    "Ecology": 79,
    "Refrigeration": 80,
    "Rocketry": 81,
    "Robotics": 82,
    "Satellites": 83,
    "Laser": 84,
    "Fiber Optics": 85,
    "Advanced Flight": 86,
    "Superconductors": 87,
    "Composites": 88,
    "Fusion": 89,
    "Genetics": 90,
    "Stealth": 91,
    "Future Tech": 92,
    "5 Gold": 1001,
}

# Items should have a defined default classification.
# In our case, we will make a dictionary from item name to classification.
DEFAULT_ITEM_CLASSIFICATIONS = {
    "The Wheel": ItemClassification.progression,
    "Agriculture": ItemClassification.progression,
    "Animal Husbandry": ItemClassification.progression,
    "Fishing": ItemClassification.progression,
    "Hunting": ItemClassification.progression,
    "Mysticism": ItemClassification.progression,
    "Archery": ItemClassification.useful,
    "Pottery": ItemClassification.progression,
    "Writing": ItemClassification.progression,
    "Sailing": ItemClassification.progression,
    "Masonry": ItemClassification.progression,
    "Mining": ItemClassification.progression,
    "Priesthood": ItemClassification.progression,
    "Bronze Working": ItemClassification.progression,
    "Polytheism": ItemClassification.progression,
    "Monotheism": ItemClassification.progression,
    "Meditation": ItemClassification.progression,
    "Monarchy": ItemClassification.progression,
    "Alphabet": ItemClassification.progression,
    "Mathematics": ItemClassification.progression,
    "Construction": ItemClassification.progression,
    "Code of Laws": ItemClassification.progression,
    "Metal Casting": ItemClassification.progression,
    "Compass": ItemClassification.progression,
    "Currency": ItemClassification.progression,
    "Horseback Riding": ItemClassification.progression,
    "Drama": ItemClassification.progression,
    "Calendar": ItemClassification.progression,
    "Iron Working": ItemClassification.progression,
    "Literature": ItemClassification.progression,
    "Aesthetics": ItemClassification.progression,
    "Banking": ItemClassification.progression,
    "Engineering": ItemClassification.progression,
    "Guilds": ItemClassification.progression,
    "Feudalism": ItemClassification.progression,
    "Machinery": ItemClassification.progression,
    "Civil Service": ItemClassification.progression,
    "Philosophy": ItemClassification.progression,
    "Optics": ItemClassification.progression,
    "Theology": ItemClassification.progression,
    "Paper": ItemClassification.progression,
    "Music": ItemClassification.progression,
    "Divine Right": ItemClassification.progression,
    "Economics": ItemClassification.progression,
    "Constitution": ItemClassification.progression,
    "Astronomy": ItemClassification.progression,
    "Democracy": ItemClassification.useful,
    "Education": ItemClassification.progression,
    "Chemistry": ItemClassification.progression,
    "Corporation": ItemClassification.progression,
    "Replaceable Parts": ItemClassification.progression,
    "Gunpowder": ItemClassification.progression,
    "Rifling": ItemClassification.progression,
    "Printing Press": ItemClassification.progression,
    "Nationalism": ItemClassification.progression,
    "Military Science": ItemClassification.useful,
    "Military Tradition": ItemClassification.useful,
    "Liberalism": ItemClassification.progression,
    "Railroad": ItemClassification.progression,
    "Electricity": ItemClassification.progression,
    "Assembly Line": ItemClassification.progression,
    "Steel": ItemClassification.progression,
    "Medicine": ItemClassification.progression,
    "Industrialism": ItemClassification.progression,
    "Communism": ItemClassification.useful,
    "Scientific Method": ItemClassification.progression,
    "Steam Power": ItemClassification.progression,
    "Fission": ItemClassification.progression,
    "Combustion": ItemClassification.progression,
    "Biology": ItemClassification.progression,
    "Physics": ItemClassification.progression,
    "Fascism": ItemClassification.useful,
    "Artillery": ItemClassification.progression,
    "Radio": ItemClassification.progression,
    "Flight": ItemClassification.progression,
    "Mass Media": ItemClassification.progression,
    "Plastics": ItemClassification.progression,
    "Computers": ItemClassification.progression,
    "Ecology": ItemClassification.progression,
    "Refrigeration": ItemClassification.progression,
    "Rocketry": ItemClassification.progression,
    "Robotics": ItemClassification.useful,
    "Satellites": ItemClassification.progression,
    "Laser": ItemClassification.progression,
    "Fiber Optics": ItemClassification.progression,
    "Advanced Flight": ItemClassification.progression,
    "Superconductors": ItemClassification.progression,
    "Composites": ItemClassification.progression,
    "Fusion": ItemClassification.progression,
    "Genetics": ItemClassification.progression,
    "Stealth": ItemClassification.progression, # Doesn't need to be if Archipelago Future Tech is removed
    "Future Tech": ItemClassification.filler, # Determine if there should be multiple in the pool
    "5 Gold": ItemClassification.filler,
}

USEFUL_WORLD_WONDER_TECHS = [
    "Communism",
    "Democracy",
    "Robotics",
]
USEFUL_NATIONAL_WONDER_TECHS = [
    "Fascism",
    "Military Tradition",
]
ANCIENT_TECHS = {
    "The Wheel",
    "Agriculture",
    "Animal Husbandry",
    "Fishing",
    "Hunting",
    "Mysticism",
    "Archery",
    "Pottery",
    "Writing",
    "Sailing",
    "Masonry",
    "Mining",
    "Priesthood",
    "Bronze Working",
    "Polytheism",
    "Meditation",
    "Monotheism",
}
CLASSICAL_TECHS = {
    "Calendar",
    "Monarchy",
    "Alphabet",
    "Mathematics",
    "Construction",
    "Code of Laws",
    "Metal Casting",
    "Compass",
    "Currency",
    "Horseback Riding",
    "Iron Working",
    "Literature",
    "Aesthetics",
    "Drama",
}
MEDIEVAL_TECHS = {
    "Feudalism",
    "Machinery",
    "Civil Service",
    "Guilds",
    "Philosophy",
    "Optics",
    "Theology",
    "Paper",
    "Music",
    "Divine Right",
    "Banking",
    "Engineering"
}
RENAISSANCE_TECHS = {
    "Economics",
    "Constitution",
    "Astronomy",
    "Democracy",
    "Education",
    "Chemistry",
    "Corporation",
    "Replaceable Parts",
    "Gunpowder",
    "Rifling",
    "Printing Press",
    "Nationalism",
    "Military Science",
    "Military Tradition",
    "Liberalism"
}
INDUSTRIAL_TECHS = {
    "Railroad",
    "Electricity",
    "Assembly Line",
    "Steel",
    "Medicine",
    "Industrialism",
    "Communism",
    "Scientific Method",
    "Steam Power",
    "Fission",
    "Combustion",
    "Biology",
    "Physics",
    "Fascism",
    "Artillery"
}
MODERN_TECHS = {
    "Radio",
    "Flight",
    "Mass Media",
    "Plastics",
    "Computers",
    "Ecology",
    "Refrigeration",
    "Rocketry",
    "Robotics",
    "Satellites",
    "Laser",
    "Fiber Optics",
    "Advanced Flight",
    "Superconductors",
    "Composites"
}
FUTURE_TECHS = {
    "Fusion",
    "Genetics",
    "Stealth",
    "Future Tech"
}

ITEM_NAME_GROUPS = {
    "Ancient Techs" : ANCIENT_TECHS,
    "Classical Techs" : CLASSICAL_TECHS,
    "Medieval Techs" : MEDIEVAL_TECHS,
    "Renaissance Techs" : RENAISSANCE_TECHS,
    "Industrial Techs" : INDUSTRIAL_TECHS,
    "Modern Techs" : MODERN_TECHS,
    "Future Techs" : FUTURE_TECHS,
}